### ISSUE TITLE
nvhda + optimus-manager

### ISSUE THREAD

**Issue by RidgeA** [hhfeuer/nvhda#15]
Hello!

Could you give an advice about how to set up this module to work together with [optimus-manager](https://github.com/Askannz/optimus-manager) properly?

I have a laptop that supports Optimus technology.
I installed `optimus-manager` and use it to switch between Intel and Nvidia GPU.
I've installed your module as well.

The issue is that upon switching to Nvidia card, regardless of the nhvda enabled I still can't see my second audio card in the output of `aplay -l`
In order to enable it, I have to switch off an then switch on back.

I think about some sort of script (or systemd unit) that will check with which GPU system loaded and enable nvhda if required. 

Is it good enough solution or could be better?

**Comment by hhfeuer** [comment]
You could either patch optimus-manager in kernel.py to do this, or create a systemd unit to start after optimus-manager.service, starting a script that checks if the nvidia module is loaded (e.g. lsmod |grep nvidia) and then turn on the audio dev.

**Comment by RidgeA** [comment]
thanks, could be closed
