### ISSUE TITLE
Error compiling with kernel 5.6

### ISSUE THREAD

**Issue by phsmith** [hhfeuer/nvhda#22]
Hi there! I've tried to compile nvhda on Arch with kernel-5.6.3-zen, gcc-9.3.0 and make-4.3., but the following error occurred:

`make -C /lib/modules/5.6.3-zen1-1-zen/build M="$(pwd)" modules
make[1]: Entering directory '/usr/lib/modules/5.6.3-zen1-1-zen/build'
  CC [M]  /home/smith/.cache/yay/nvhda-dkms-git/src/nvhda/nvhda.o
/home/smith/.cache/yay/nvhda-dkms-git/src/nvhda/nvhda.c: In function ‘nvhda_init’:
/home/smith/.cache/yay/nvhda-dkms-git/src/nvhda/nvhda.c:250:60: error: passing argument 4 of ‘proc_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  250 |     acpi_entry = proc_create("nvhda", 0664, acpi_root_dir, &nvhda_fops);
      |                                                            ^~~~~~~~~~~
      |                                                            |
      |                                                            struct file_operations *
In file included from ./include/acpi/acpi_bus.h:83,
                 from ./include/linux/acpi.h:32,
                 from /home/smith/.cache/yay/nvhda-dkms-git/src/nvhda/nvhda.c:32:
./include/linux/proc_fs.h:64:24: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
   64 | struct proc_dir_entry *proc_create(const char *name, umode_t mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
      |                        ^~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:268: /home/smith/.cache/yay/nvhda-dkms-git/src/nvhda/nvhda.o] Error 1
make[1]: *** [Makefile:1683: /home/smith/.cache/yay/nvhda-dkms-git/src/nvhda] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.6.3-zen1-1-zen/build'
make: *** [Makefile:13: default] Error 2`

I managed to compile successfully with the following patch.
[nvhda.c.patch.txt](https://github.com/hhfeuer/nvhda/files/4472426/nvhda.c.patch.txt)

**Comment by vfbsilva** [comment]
Nvhda is on aur

Em seg, 13 de abr de 2020 21:00, Phillipe Smith <notifications@github.com>
escreveu:

**Comment by phsmith** [comment]
> Nvhda is on aur

@vfbsilva the compilation error is from the package that is in the AUR.

**Comment by nixingyang** [comment]
@phsmith The [package](https://aur.archlinux.org/packages/nvhda-dkms-git/) in AUR is buggy and unmaintained. I created my own [PKGBUILD](https://github.com/nixingyang/Miscellaneous-Projects/blob/master/nvhda/PKGBUILD) file and it works fine.

**Comment by hhfeuer** [comment]
Fixed now.
Out of interest, what's the use-case on recent kernels, the hda device should now be unconditionally enabled by a pci quirk?

**Comment by phsmith** [comment]
> Fixed now.
> Out of interest, what's the use-case on recent kernels, the hda device should now be unconditionally enabled by a pci quirk?

@hhfeuer didn't know about that. The reality is that I'm rarely put HDMI in use, I've just got the compilation error when upgrading the system and tried to solve.
