### ISSUE TITLE
The included systemd scripts are not working

### ISSUE THREAD

**Issue by asemarafa** [hhfeuer/nvhda#5]
Hello

ExecStart=/bin/echo "ON" >/proc/acpi/nvhda
ExecStart=/bin/echo "OFF" >/proc/acpi/nvhda

Just echos '>' and doesn't perform actual output redirection , this is in Arch Linux systemd 239, not sure if it used to work on earlier versions before

Please modify to the below and it should work 

ExecStart=/bin/bash -c "/bin/echo ON >/proc/acpi/nvhda"
ExecStart=/bin/bash -c "/bin/echo OFF >/proc/acpi/nvhda"

**Comment by hhfeuer** [comment]
Thanks for reporting. Changed the scripts accordingly.
